window:
  opacity: 0.75

  dimensions:
    columns: 150
    lines: 50
  padding:
    x: 20
    y: 20

font:
  normal: 
    family: Fira Code
    style: Bold
  
  italic: 
    family: Fira Code
    style: Italic
  
  bold:
    family: Fira Code
    style: Bold

shell:
 program: fish

colors:
  primary:
    forground:  '#ebdbb2'
    background: '#282828'
  
  normal:
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'

  bright:
    red:    '#fb4934'
    green:  '#b8bb26'
    yellow: '#fabd2f'
    blue:   '#83a598'
    purple: '#d3869b'
    aqua:   '#8ec07c'
    orange: '#fe8019'

  dim:
    red:     '#9d0006'
    green:   '#79740e' 
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#af3a03'

draw_bold_text_with_bright_colors: true